export const pirates = [
  "Captain Blackheart",
  "Mad Anne Bonny",
  "Salty Jack Rackham",
  "Bloody Ben Stede",
  "One-Eyed Ollie",
  "Silent Sarah Graves",
  "The Sea Wolf",
  "Calico Joe",
  "Dread Pirate Roberts",
  "Barnacle Bill",
  "Scarlet Jane",
  "Fearsome Frank",
  "Blackbeard's Ghost",
  "Mistress Mary Read",
  "Groggy George",
  "Old Man Hook",
  "Stormy Pete",
  "The Crimson Queen",
  "Tide-Runner Tim",
  "Pegleg Polly",
];
